# Generated by Django 5.2.6 on 2025-10-03 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='notify_before_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitcheckin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='notify_before_days',
            field=models.IntegerField(default=1),
        ),
    ]
