# Generated by Django 5.2.6 on 2025-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goal_notify_before_days_habit_last_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='bind_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
