# Generated by Django 5.2.6 on 2025-10-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pending2fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='main.goaltemplate')),
            ],
        ),
    ]
