# Generated by Django 5.2.6 on 2025-10-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subgoaltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
