# Generated by Django 5.2.6 on 2025-10-28 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_telegramprofile_notifications_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(default=0)),
                ('tuesday', models.IntegerField(default=0)),
                ('wednesday', models.IntegerField(default=0)),
                ('thursday', models.IntegerField(default=0)),
                ('friday', models.IntegerField(default=0)),
                ('saturday', models.IntegerField(default=0)),
                ('sunday', models.IntegerField(default=0)),
                ('week_start', models.DateField(default=django.utils.timezone.now)),
                ('total_activities', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
