# Generated by Django 5.2.6 on 2025-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending2fa',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
