# Generated by Django 5.2.6 on 2025-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pending2fa_telegram_message_id'),
        ('main', '0008_pending2fa_declined'),
    ]

    operations = [
    ]
