# Generated by Django 5.2.6 on 2025-11-03 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20251028_1516'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Активний тех адміністратор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tech_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тех адміністратор',
                'verbose_name_plural': 'Тех адміністратори',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В процесі'), ('resolved', 'Вирішено'), ('closed', 'Закрито')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('urgent', 'Срочний')], default='medium', max_length=20, verbose_name='Приорітет')),
                ('problem_type', models.CharField(default='2fa_help', max_length=50, verbose_name='Тип проблеми')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Вирішено')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки адміністратора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to='main.techadmin', verbose_name='Призначено')),
            ],
            options={
                'verbose_name': 'Повідомлення в підтримку',
                'verbose_name_plural': 'Повідомлення в підтримку',
                'ordering': ['-created_at'],
            },
        ),
    ]
