# Generated by Django 5.2.6 on 2025-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittemplate',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
