# Generated by Django 5.2.6 on 2025-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_habittemplate_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='was_resolved',
            field=models.BooleanField(default=False, verbose_name='Was Resolved'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
    ]
