# Generated by Django 5.2.6 on 2025-11-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_supportmessage_was_resolved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingpasswordreset',
            options={'verbose_name': 'Password reset', 'verbose_name_plural': 'Password resets'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Support message', 'verbose_name_plural': 'Support messages'},
        ),
        migrations.AlterModelOptions(
            name='techadmin',
            options={'verbose_name': 'Tech admin', 'verbose_name_plural': 'Tech admins'},
        ),
        migrations.AddField(
            model_name='habit',
            name='max_streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pendingpasswordreset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='pendingpasswordreset',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='pendingpasswordreset',
            name='new_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='New password'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin notes'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to='main.techadmin', verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='problem_type',
            field=models.CharField(default='2fa_help', max_length=50, verbose_name='Problem type'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved at'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='was_resolved',
            field=models.BooleanField(default=False, verbose_name='Was resolved'),
        ),
        migrations.AlterField(
            model_name='techadmin',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active tech admin'),
        ),
    ]
