# Generated by Django 5.2.6 on 2025-11-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_notification_notification_type_and_more'),
        ('main', '0016_alter_pendingpasswordreset_options_and_more'),
    ]

    operations = [
    ]
