# Generated by Django 5.2.6 on 2025-11-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20251112_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='habittemplate',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='subgoaltemplate',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
