# Generated by Django 5.2.6 on 2025-11-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_goal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltemplate',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='habittemplate',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
